### ISSUE TITLE
go-sbot panics on first run due to missing ~/.ssb-go & config changes?

### ISSUE THREAD

**Issue by decentral1se** [ssbc/go-ssb#144]
> ➜  ssb (master) ✗ ./go-sbot
level=info t=85.905µs event="read config" msg="no config detected" path=/home/d/.ssb-go/config.toml
t=872.892µs event=panic location=main-panic panicLog=panics/main-panic175805834 err="open /home/d/.ssb-go/running-config.json: no such file or directory"

Starting `./go-sbot` after https://github.com/cryptoscope/ssb/commit/27a936da805d127f22af539760849e03f07358e6 now results in a panic. Before https://github.com/cryptoscope/ssb/commit/27a936da805d127f22af539760849e03f07358e6, `go-sbot` would bootstrap the `~/.ssb-go` directory for you (that's the work-around for now :))

From https://github.com/cryptoscope/ssb/blob/master/docs/quick-start.md#run-go-sbot I see that the config step is optional? Could take a stab at a fix if someone can show the way :pray:

**Comment by cryptix** [comment]
cc @cblgh

**Comment by cblgh** [comment]
Will look into a repro & patch for this in the coming week, thanks for the ping!
