### ISSUE TITLE
I implemented an ssb with Rust, but encountered some problems ......

### ISSUE THREAD

**Issue by Cupnfish** [ssbc/go-ssb#156]
Hello! I would like to ask some questions. I have recently implemented an ssb using Rust, and I am currently having some problems, and I would like to ask the ssbc engineers.

Just to be clear, the version I implemented initially was implemented according to [this document](https://ssbc.github.io/scuttlebutt-protocol-guide/#rooms-tunnel).

 Most of the documentation is already implemented, but I'm currently confused about the synchronization part. I tried to send a `createHistoryStream` request by filtering out all the feeds I wanted to know from the friends-graph when creating the connection. But I didn't get the expected result, and interacting with patchwork returned a bunch of `createHistoryStream` requests, but didn't return the result I wanted to me. Interacting with manyverse returned the results I wanted, but didn't send me the `createHistoryStream` request.

I'm not sure if I'm syncing the right way, is there any documentation on this that I can view, I've searched most of the documentation but none of it has detailed documentation on synchronization of multiple ends that I can check, currently reading various source code for ssb, but I don't know much about js and go myself, reading these is slow.

**Comment by Cupnfish** [comment]
Sorry, shortly after posting this issue, I found this: https://github.com/ssbc/ssb-ebt

**Comment by mplorentz** [comment]
Hey @Cupnfish, nice work on the Rust implementation! EBT replication is hard to implement. @boreq has started writing some docs for it [here](http://dev.planetary.social/replication/ebt.html), but I don’t think they are complete. If you have more questions you could try jumping into this Matrix room: `#scuttlebutt:libera.chat`.

**Comment by boreq** [comment]
>don’t think they are complete

They very much aren't complete but they are better than nothing I think.

**Comment by Cupnfish** [comment]
> Hey @Cupnfish, nice work on the Rust implementation! EBT replication is hard to implement. @boreq has started writing some docs for it [here](http://dev.planetary.social/replication/ebt.html), but I don’t think they are complete. If you have more questions you could try jumping into this Matrix room: `#scuttlebutt:libera.chat`.

Great, thanks so much!
