### ISSUE TITLE
Migrate old module URLs to new ssbc/... ones

### ISSUE THREAD

**Issue by decentral1se** [ssbc/go-ssb#160]
https://github.com/ssbc/go-ssb/pull/159#issuecomment-1269620057

/cc @masukomi

**Comment by masukomi** [comment]
👍 I'm hesitant to tackle this one myself because i barely touch go code these days, and have no real clue what the current standards are for stuff like this. Also, I just don't want to break things. ;)

**Comment by decentral1se** [comment]
Sure thing @masukomi! I actually ran into an issue where the deps in go-ssb are refering to old versions of underlying libs and it's causing tests to break. One small fix is https://github.com/ssbc/go-ssb/pull/162 but the real fix is to upgrade the lib. I might take a stab at this soon.

**Comment by decentral1se** [comment]
Seems like https://github.com/ssbc/go-ssb-refs/pull/2 is fine then, so the renaming approach can go ahead...

Will map out the included repos here from the listing here https://github.com/orgs/ssbc/repositories?q=&type=all&language=go&sort= and then send out a bunch of rename PRs. Once everything is merged, I can switch over the URLs in the go.mod / imports here and we're good :crossed_fingers: 

Having the test suite passing again will help https://github.com/ssbc/go-ssb/pull/167 avoid breaking the world i hope
