### ISSUE TITLE
Increase speed of CI

### ISSUE THREAD

**Issue by decentral1se** [ssbc/go-ssb#168]
1. It's hard to run it locally (requires sodium-native/nodejs/npm/etc.)
2. It takes aggees to run in the action so getting feedback means waiting ~ 20 mins

We could...

Use a smaller image:

https://github.com/ssbc/go-ssb/blob/ca39754da2beb8d21ad76ec885b45709fb7b4176/.github/workflows/go.yml#L16

Pre-install required Node on image:

https://github.com/ssbc/go-ssb/blob/ca39754da2beb8d21ad76ec885b45709fb7b4176/.github/workflows/go.yml#L19

Pre-install required Go on image:

https://github.com/ssbc/go-ssb/blob/ca39754da2beb8d21ad76ec885b45709fb7b4176/.github/workflows/go.yml#L24

Pre-install node ssb stack (killer sodium-native installs!):

https://github.com/ssbc/go-ssb/blob/ca39754da2beb8d21ad76ec885b45709fb7b4176/.github/workflows/go.yml#L39

**Comment by staltz** [comment]
> killer sodium-native installs

It's probably because it's compiling libsodium (C).

**Comment by decentral1se** [comment]
Seems possiblle to run stuff in a container then:

> https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container
