### ISSUE TITLE
sbotcli --uses on invite create command is broken

### ISSUE THREAD

**Issue by stevenroose** [ssbc/go-ssb#181]
When calling either `./go-ssb/cmd/sbotcli/sbotcli invite create --uses=100` or `./go-ssb/cmd/sbotcli/sbotcli invite create --uses 100`, server reports `t=1h43m59.223289096s unit=legacyInvites invite=created uses=1`

**Comment by decentral1se** [comment]
Thanks for the report! Can reproduce, smells like a bug :+1:

**Comment by decentral1se** [comment]
https://github.com/ssbc/go-ssb/pull/194
