### ISSUE TITLE
Which feed formats do we support?

### ISSUE THREAD

**Issue by decentral1se** [ssbc/go-ssb#199]
Very open question, I'm not sure myself.

Was going to append "in core" to the title but I'm not sure what "core" is! It could be something to sketch out.

I'm approaching it from the perspective of 1) increasing stability 2) making maintenance easier.

From the mainnet:

> Following [%dNOiE...](https://github.com/ssbc/go-ssb/issues/%dNOiEnNfec5EIYPAyExEOiiRPd+vSwehtzLHJh7yCnk=.sha256) & [%jaAjy...](https://github.com/ssbc/go-ssb/issues/%jaAjyOj5wiULHurZfEQkSEspddJuYJ5v4e2icAVkRqs=.sha256) where is [#gabbygrove](https://github.com/ssbc/go-ssb/issues/new#gabbygrove) at and should things like [#go-ssb](https://github.com/ssbc/go-ssb/issues/new#go-ssb) support it? I’m kind of on the look-out for experiments and other loose ends that could be moved out of go-ssb for the purposes of making it easier to manage / work with. Any pointers/tips are much appreciated ✌ [#go-ssb-dev](https://github.com/ssbc/go-ssb/issues/new#go-ssb-dev)

> I don’t think anyone uses gabbygrove in production, but I could be wrong. Do you know how to move it out as a new module that could be “plugged in”? This could help make the core go-ssb more flexible. While you’re at it, it would be great to have more flexible to “plug in” new feed formats. Note that besides classic and gabbygrove, go-ssb also supports bendybutt. See go-metafeeds.

**Comment by staltz** [comment]
If I may suggest, at least consider bendybutt-v1 to be very important because metafeeds in the future are going to be essentially SSB "2.0" and bendybutt-v1 is non-negotiable in that world.

**Comment by decentral1se** [comment]
Thanks for that input @staltz! Reading https://dev.scuttlebutt.nz/#/golang/?id=receive-log again:

> Since go-ssb also not only supports the json-based feed format but also [gabbygrove](https://pkg.go.dev/go.mindeco.de/ssb-gabbygrove?tab=overview), the [multimsg package](https://pkg.go.dev/go.cryptoscope.co/ssb@v0.0.0-20201008153016-a00fdfeccb87/message/multimsg) is used to support both and more in the future.

So, the `multimsg` package is already the plug in/out interface that we can use. Long way off from doing with this so I will close it for now. Did learn something though :smiley:
