### ISSUE TITLE
Limit flag for tangles.thread RPC returns n+1

### ISSUE THREAD

**Issue by mycognosist** [ssbc/go-ssb#211]
Currently testing `tangles.thread` using `golgi` and I'm seeing n+1 behaviour when passing the `limit` option.

E.g. Limit == 1, 2 messages returned. Limit == 2, 3 messages returned etc.

When limit == 0, all messages returned.

I am seeing the same behaviour when using `sbotcli replies`.

So I guess it's behaving as if I asked for the root message _plus_ the number of messages specified by the `limit` option. Maybe this is intended?

**Comment by mycognosist** [comment]
Labelled as `question` because I'm not sure it's a bug.

**Comment by decentral1se** [comment]
@mycognosist

From a quick scan of the code, I see that `limit=0` gets set to `-1` meaning, all of it - that corresponds with what you're seeing. And then for anything > 0, it does indeed correspond to root + message replies. The logic counts down the limit one by one until it hits 0. So, that does then seem intended.

Do you need to only get the specific root message? You can use `sbotcli get` then, I guess.

I guess we could really improve the `sbotcli` documention here. It's basically undocumented in large parts?

**Comment by mycognosist** [comment]
@decentral1se 

> And then for anything > 0, it does indeed correspond to root + message replies. The logic counts down the limit one by one until it hits 0. So, that does then seem intended.

Thanks for the sanity check. I think this is one of those cases where clear documentation of the behaviour would be super helpful; in other streams (such as `createHistoryStream`) a `limit` of 2 would only return 2 messages, so there's room for confusion 😅 

Maybe we could do an `sbotcli` documentation sprint sometime, if you're up for it? Would probably only take a couple of days to improve the coverage significantly.
