### ISSUE TITLE
Config.toml repo not behaving as expected

### ISSUE THREAD

**Issue by KyleMaas** [ssbc/go-ssb#215]
Ran into an issue where if the repo was specified in config.toml as its default of:

```
repo = '.ssb-go'
```

...and go-sbot was run from anywhere other than the home directory base, it would instead create a new repo directory inside of the current directory called `.ssb-go`.  I had expected this to resolve to that directory inside of the user's home directory, not relative to whatever the current working directory is, so expectation broken.  To fix this, I tried changing it to:

```
repo = '~/.ssb-go'
```

This, then, made a directory in the current directory called `~` and placed a new `.ssb-go` directory inside of it, rather than resolving that to the home directory.  So, once again, expectation broken.

The way I've found that works is to specify it as a full path from root.  That works.  But I figured I'd better note this experience because I doubt I'll be the only one to encounter this.

**Comment by decentral1se** [comment]
Ah yeh, that's a bug, we should probably be parsing the `~` -> absolute rooth path if it's in the string or otherwise just absolute path-izing it. Thanks for the report! /cc @cblgh if you fancy patching this re: config implementation.

**Comment by KyleMaas** [comment]
No problem.  Sometimes it helps to have the eyes of a new and clueless user.

**Comment by cblgh** [comment]
@decentral1se oh yeah, i'll have a look at this :)

**Comment by KyleMaas** [comment]
Awesome.  Thanks!
