### ISSUE TITLE
TLS Certificates for WebSockets

### ISSUE THREAD

**Issue by KyleMaas** [ssbc/go-ssb#216]
Is there a way to specify TLS certificates for secure WebSockets?  So far I'm not seeing anything that would point to that having been implemented.

**Comment by decentral1se** [comment]
Unsure! But having a dig in https://github.com/ssbc/go-ssb/blob/master/network/websocket.go & https://pkg.go.dev/github.com/gorilla/websocket#section-readme might shed some light on this. If you figure it out we could see about threading this through the `go-sbot` options.

**Comment by KyleMaas** [comment]
Couldn't find a great way to actually test this without adding the options for the cert and key files, so I did that, too.  Seems to work okay here - I can connect to it via `wss:` in `ssb-browser-demo`.
