### ISSUE TITLE
Document sbotcli

### ISSUE THREAD

**Issue by decentral1se** [ssbc/go-ssb#217]
@mycognosist 

Following on from https://github.com/ssbc/go-ssb/issues/211, let's gather ourselves here. I'm down to help.

`sbotcli` is using [`urfave`](https://github.com/urfave/cli) // https://cli.urfave.org for the CLI library, so that is the start to look at how to do documentation. It's not a fully worked out library and there are some gotchas :upside_down_face: One handy reference might be [`abra`](https://git.coopcloud.tech/coop-cloud/abra/src/branch/main/cmd/abra) which is using the same lib and has a lot more documentation in place.

PRs on the way hopefully this week also from my side.

**Comment by mycognosist** [comment]
@decentral1se 

Awesome! Thanks for the `abra` reference, that's really helpful (I'd looked at the `urfave` docs but couldn't find clear example usage).

Just so we don't duplicate efforts, I'm currently working on adding a simple one-liner usage description for each command. That way, when you call `sbotcli` without any args, you at least get a list of commands where each is briefly described.

I'll aim to make a PR by the end of today and we can always go back-and-forth on it until we're happy :)

**Comment by decentral1se** [comment]
I think https://github.com/ssbc/go-ssb/pull/224 covers a lot of the issues I had when I first started using `sbotcli`, e.g. what the heck do I pass as `<args>` :sweat_smile: I think that PR at least lays the groundwork for folks to drop more examples into the `Description: ...` of each command which I think would be great to add. I added some but haven't used all the commands.

**Comment by mycognosist** [comment]
Agreed, it's already so much better than it was. I think my ultimate goal / dream is for `sbotcli` to be completely self-documenting; no need to jump into a browser and search the bowels of the interwebz for arcane Scuttlebutt docs. Step by step.

**Comment by mycognosist** [comment]
Just merged https://github.com/ssbc/go-ssb/pull/240 🎉 

I think we might be able to close this issue now? There's always room for improvement but I think we have achieved an excellent amount of coverage.

**Comment by mycognosist** [comment]
Posted in the Scuttleverse to keep the Butts in the loop:

`%JQPdgaaLAYXojsOCS/hsWI+c+bDLCZfUolzUoP6Eh3w=.sha256`

**Comment by decentral1se** [comment]
So nice! Wonderful praxis @mycognosist!
