### ISSUE TITLE
Default config.toml not created on go-sbot startup

### ISSUE THREAD

**Issue by mycognosist** [ssbc/go-ssb#223]
I would expect a `config.toml` to be generated when `go-sbot` is run for the first time (`.ssb-go/config.toml`). This is not currently the case. I have a feeling it used to work but can't remember specifics. For now I'm generating a `config.toml` file manually.

**Comment by decentral1se** [comment]
@mycognosist 

I believe a `.json` dump should still get persisted:

https://github.com/ssbc/go-ssb/blob/afb21d1ac82e1fc7d556a5de1fc214c2a797f451/cmd/go-sbot/main.go#L184-L185

But I don't think the `.toml` does. It is just read? Would it be handy to auto-generate one with defaults?

**Comment by decentral1se** [comment]
https://github.com/ssbc/go-ssb/pull/246
