### ISSUE TITLE
Invite create RPC method now expects args as an array

### ISSUE THREAD

**Issue by mycognosist** [ssbc/go-ssb#235]
I'm in the process of (re)testing invites in [golgi](https://git.coopcloud.tech/golgi-ssb/golgi) and learned that the args for `invite.create` are now expected in the form of an array (was previously an object).

I believe the change was introduced in https://github.com/ssbc/go-ssb/pull/194 (see L52 of `plugins/legacyinvites/master.go`):

```diff
- var args CreateArguments
+ var args []CreateArguments
```

When running the (unchanged) golgi invites example, I encountered the following error from go-sbot:

`unable to receive invite create payload: json: cannot unmarshal object into Go value of type []legacyinvites.CreateArguments`

The command succeeded as expected after changing [the kuska RPC code](https://github.com/Kuska-ssb/ssb/blob/master/src/api/helper.rs#L331) (used by golgi under the hood) to send the args as an array instead of an object.

-----

This issue is merely a way of flagging this for some future traveller who may have been tripped up by the change.

-----

Related:

https://git.coopcloud.tech/golgi-ssb/golgi/issues/42

**Comment by decentral1se** [comment]
Aha yes, apologies for the breakage! I will make sure to flag this stuff in future more clearly. Shall we take advantage of this issue to brainstorm some MUXRPC documentation in `go-ssb`? Also related to thoughts in https://github.com/ssbc/go-ssb/pull/221#issuecomment-1328716087. I think we could all benefit from it. I guess I just need to write it up manually?

**Comment by mycognosist** [comment]
Closing this now (just wanted a record in the issues). Moving discussion over to #238
