### ISSUE TITLE
TestBadger still flaking

### ISSUE THREAD

**Issue by decentral1se** [ssbc/go-ssb#266]
https://github.com/ssbc/go-ssb/actions/runs/3726907359/jobs/6320652343

> 2022/12/18 22:38:59 [margaret/indexes/badger] overwrote batch limit 0
> --- FAIL: TestBadger (0.15s)
>     --- FAIL: TestBadger/scene1 (0.11s)
>         builder_test.go:234: 
>             	Error Trace:	/home/runner/work/go-ssb/go-ssb/graph/builder_test.go:234
>             	Error:      	Not equal: 
>             	            	expected: 3
>             	            	actual  : 2
>             	Test:       	TestBadger/scene1
>     builder_test.go:131: closed scenary
> FAIL
> FAIL	github.com/ssbc/go-ssb/graph	0.159s
> FAIL
> make: *** [Makefile:22: test] Error 1
> Error: Process completed with exit code 2.

**Comment by KyleMaas** [comment]
Same problem we've had in most other flaky tests - the indexes fall behind and the test is looking for data from them.  Difficulty with this is that the test doesn't use `sbot` but instead goes its own way with indexes, so we don't have the wait-for-indexes functionality available in this test.
