### ISSUE TITLE
TestInvalidFuzzed is flaky

### ISSUE THREAD

**Issue by KyleMaas** [ssbc/go-ssb#284]
This has apparently been happening enough that it's part of the code for the test:

https://github.com/ssbc/go-ssb/blob/master/message/legacy/verify_invalid_test.go#L20

Where it's crashing is here:

https://github.com/ssbc/go-ssb/blob/master/message/legacy/verify_invalid_test.go#L82

So...I think we've got some data in `testdata-fuzzed.json` which is invalid.

See #237

**Comment by KyleMaas** [comment]
Specifically, it's this message:

https://github.com/ssbc/go-ssb/blob/9fe9976db4dff44f35034f6e76a539b381933ce4/message/legacy/testdata-fuzzed.json#L90

**Comment by KyleMaas** [comment]
Ah, it has a signature that's too long and is overflowing the decoding buffer.

**Comment by KyleMaas** [comment]
Yeah, I think this is actually a bug in the test data.  ed25519 signatures should always be the same length, AFAIK.  In the data, they're not.

**Comment by KyleMaas** [comment]
@decentral1se 

Mind sanity checking my assumptions on this?  From what I understand, an ed25519 signature should *always* result in an output of 64 bytes (`SignatureSize` from [crypto/ed25519](https://pkg.go.dev/crypto/ed25519) ), correct?

**Comment by decentral1se** [comment]
@KyleMaas I think you're on to something suspecting the test data!

For the length, yep, it's also tested also further down:

https://github.com/ssbc/go-ssb/blob/d83e578b178fe80de2b74f177f843c6251d5aec6/message/legacy/testdata-fuzzed.json#L914-L918

Removing that entry does start to make the test pass again. So perhaps we just need to set some guard deeper down in the stack to avoid the explosion and bubble up an error? I guess the code was changed at some point and stopped bubbling errors up...

Somewhere here?

https://github.com/ssbc/go-ssb/blob/d83e578b178fe80de2b74f177f843c6251d5aec6/message/legacy/signature.go#L24

**Comment by KyleMaas** [comment]
@decentral1se 

I tried adding a check here in my experimental branch:

https://github.com/ssbc/go-ssb/pull/285/commits/532060cc3eff111443ebbaf344a842bccce9b1d0

But it's still broken.

However, knowing that it's always supposed to decode as 64 bytes definitely gives me something to go on.

**Comment by KyleMaas** [comment]
I think I figured it out.  It's due to a bug related to data being padded and the length measurements not taking that into account.

**Comment by KyleMaas** [comment]
So...not a problem with the test data.  It was actually a bug in the signature check due to problems with how the data decoded with padding.  So this was actually quite useful for catching that.

**Comment by decentral1se** [comment]
Brilliant @KyleMaas! Great to get a fix out for something so core as sig validation :clap: :clap: :clap:

**Comment by KyleMaas** [comment]
Thanks!  Glad we could get this one picked off the list.
