### ISSUE TITLE
Fix REUSE badge

### ISSUE THREAD

**Issue by KyleMaas** [ssbc/go-ssb#305]
"Project not registered", as linked to by the homepage:

https://api.reuse.software/info/github.com/ssbc/go-ssb

**Comment by decentral1se** [comment]
> # MISSING COPYRIGHT AND LICENSING INFORMATION
> The following files have no copyright and licensing information:
> * .github/dependabot.yml
> * cmd/go-sbot/config.go
> * cmd/go-sbot/config_test.go
> * cmd/go-sbot/default-config.toml
> * docs/config.md
> * docs/faq.md
> * internal/refactors/ref2sigil-blobs.go
> * internal/refactors/ref2sigil-msgs.go
> * internal/refactors/ref2sigil-short.go
> * internal/refactors/ref2sigil.tpl.go
> * tests/local_fork_test.go

**Comment by decentral1se** [comment]
> # SUMMARY
> 
> * Bad licenses:
> * Deprecated licenses:
> * Licenses without file extension:
> * Missing licenses:
> * Unused licenses:
> * Used licenses: AGPL-3.0-only, Apache-2.0, CC-BY-NC-4.0, CC0-1.0, MIT
> * Read errors: 0
> * Files with copyright information: 333 / 333
> * Files with license information: 333 / 333
> 
> Congratulations! Your project is compliant with version 3.0 of the REUSE Specification :-)

**Comment by KyleMaas** [comment]
Awesome!
