### ISSUE TITLE
sbotc <-> go-sbot bad dialog report

### ISSUE THREAD

**Issue by zicmama** [ssbc/go-ssb#62]
When executing this commands, it seems some index searching are missing?
```
sbotc backlinks.read '{"query":[{"$filter":{"dest":"#zenytv","value":{"content":{"type":"post"}},"timestamp":{"$gt":'"1599682818301"'}}}]}'
{"name":"Error","message":"no such command: backlinks.read","stack":""}
```
```
self_name=$(sbotc query.read '{"query":[{"$filter":{"value":{"author": "'"$self"'", "content":{"type":"about", "about": "'"$self"'"}}}}]}' | jq -r .value?.content?.name | grep -v null | tail -n 1)
{"name":"Error","message":"no such command: query.read","stack":""}
```

Is it normal?
Is there a CLI commands listing?

thanks

**Comment by cryptix** [comment]
Sorry, yes, this is normal. I should add a list of supported methods to the README.

Right now, apart from createHistoryStream and messagesByType there only is a custom tangles source method. All those extra ones (not needed for replication) need to be enabled with the -fatbot flag on go-sbot.

Also note that gt/le etc are based on sequence numbers, not timestamps like in JS land.


I'm not interested in adding 1:1 support for ssb-query/map-filter-reduce syntax. Wouldn't mind a contributions for it but I know it's very involved work..

I'm loosely thinking of adopting the jitdb query syntax but it's still a bit too far out to say just yet.

**Comment by cryptix** [comment]
ps: the latest working branch is wip-browser-demo which features support for @arj03's work.

It hardcodes a method for `type:x AND author:y` which does what your query.read method does but like I said, no abstract query language just yet.

It also supports the manifest method, which shows all the supported muxrpc calls.

With -fatbot there also are methods for names that make about lookups very fast since they are based on a reduced index.

**Comment by zicmama** [comment]
Thank you @cryptix 
Even if I did not totaly understood what you said. I think this means I cannot use sbotc with go-sbot.
I would be greatly enjoyed with "list of supported methods" and examples. And explain what -fatbot option is and how to make use of it?

peace & gratitude

**Comment by cryptix** [comment]
Oh sorry. I know, it's pretty intricate... to be clear: you _should_ be able to use sbotc with go-sbot, you just have to be extra careful about the (muxrpc) methods that you use!

what should work for instance are `publish`, `blobs.want` or `createHistoryStream`. The more advanced database queries like, `query.read`, `links(2)` and the like... not so much, sadly.

Let me pump this thread again once I have those examples for you.

re fatbot: start the server like this: `go-sbot -fatbot`, then you you should be able to call `sbotcli messagesByType post` for instance.

note to self: I need to try sbotc
